spring:
  application:
    name: second-client-app
  cloud:
    config:
      uri: http://config-server:8888 
  config:
    import: configserver:http://config-server:8888
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
